In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer 
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [4]:
df1 = pd.read_csv("Train.csv")
print(df1.info())
df1.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   review  40000 non-null  object
 1   label   40000 non-null  object
dtypes: object(2)
memory usage: 625.1+ KB
None


review label
0  mature intelligent and highly charged melodram...   pos
1  http://video.google.com/videoplay?docid=211772...   pos
2  Title: Opera (1987) Director: Dario Argento Ca...   pos
3  I think a lot of people just wrote this off as...   pos
4  This is a story of two dogs and a cat looking ...   pos
5  Steve Carell comes into his own in his first s...   pos
6  I'm only going to write more because it's requ...   neg
7  OK, it was a "risky" move to rent this flick, ...   neg
8  Cannibalism, a pair of cinematic references to...   pos
9  This is one of the great modern kung fu films....   pos

In [5]:
df2 = pd.read_csv("Test.csv")
print(df2.info())
df2.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   review  10000 non-null  object
dtypes: object(1)
memory usage: 78.2+ KB
None


review
0  Remember those old kung fu movies we used to w...
1  This movie is another one on my List of Movies...
2  How in the world does a thing like this get in...
3  "Queen of the Damned" is one of the best vampi...
4  The Caprica episode (S01E01) is well done as a...
5  I usually really enjoy Steven Seagal movies. T...
6  Jiøí Trnka made his last animated short an i...
7  This is so bad it will be my contribution to t...
8  Watching this hilariously retro but very enter...
9  Excellent political thriller, played much quie...

In [6]:
# label column of of training data
y = df1.iloc[:,-1]
print(y)

0        pos
1        pos
2        pos
3        pos
4        pos
        ... 
39995    neg
39996    neg
39997    neg
39998    pos
39999    pos
Name: label, Length: 40000, dtype: object


In [7]:
le = LabelEncoder()
y = le.fit_transform(y).reshape(-1,1).ravel()
print(y.shape)
print(y)

(40000,)
[1 1 1 ... 0 1 1]


### tokenization, stopword removal and lemmatization

In [8]:
#nltk.download('stopwords')
#nltk.download('punkt')
#nltk.download('wordnet')
stop_words = stopwords.words("english")
lem = WordNetLemmatizer()
for index,row in df1.iterrows():
    curr_sent = row["review"]
    curr_sent = re.sub(r'[^\w\s]', "" ,curr_sent)
    l1 = word_tokenize(curr_sent)
    l1 = [ lem.lemmatize(word).lower() for word in l1 if not word in stop_words ]
    new_sent = ""
    for w in l1:
        new_sent = new_sent + " " + w
    row["review"] = new_sent

In [9]:
df1.head(10)

review label
0   mature intelligent highly charged melodrama u...   pos
1   httpvideogooglecomvideoplaydocid2117721666500...   pos
2   title opera 1987 director dario argento cast ...   pos
3   i think lot people wrote another one tom crui...   pos
4   this story two dog cat looking way back homeo...   pos
5   steve carell come first starring role 40 year...   pos
6   im going write required however summary i put...   neg
7   ok risky move rent flick i thought i nothing ...   neg
8   cannibalism pair cinematic reference delicate...   pos
9   this one great modern kung fu film a lot revi...   pos

In [9]:
df1.loc[300,"review"]

' this movie far best ever i think whoever shot sony handheld camera genius special effect spectacular especially chicken breast heartthank goodness movie cost dollar rent also green toxic boob discharge amazingi could shot movie friend high school i would recommend movie anyone might want kill instead watching i also feel like move porn star trying make legitimate movie businessgive larz'

In [10]:
for index,row in df2.iterrows():
    curr_sent = row["review"]
    curr_sent = re.sub(r'[^\w\s]', "" ,curr_sent)
    l1 = word_tokenize(curr_sent)
    l1 = [ lem.lemmatize(word).lower() for word in l1 if not word in stop_words ]
    new_sent = ""
    for w in l1:
        new_sent = new_sent + " " + w
    df2.loc[index,"review"] = new_sent    # same fucntion as the one in training set

In [11]:
df2.head(10)

review
0   remember old kung fu movie used watch friday ...
1   this movie another one list movies not to bot...
2   how world thing like get dvd player home how ...
3   queen damned one best vampire movie i ever se...
4   the caprica episode s01e01 well done pilot re...
5   i usually really enjoy steven seagal movie th...
6   jiãã trnka made last animated short indictmen...
7   this bad contribution next bad movie party i ...
8   watching hilariously retro entertaining caree...
9   excellent political thriller played much quie...

In [12]:
cvec = CountVectorizer(max_features = 10000)



In [13]:
X1 = df1["review"]
X1= cvec.fit_transform(X1).toarray()
print(type(X1),X1.shape)
X1

<class 'numpy.ndarray'> (40000, 10000)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [14]:
X2 = df2["review"]
X2= cvec.transform(X2).toarray()
print(type(X2),X2.shape)
X2

<class 'numpy.ndarray'> (10000, 10000)


array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X1,y,test_size=0.2,random_state=21)

In [16]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(32000, 10000) (32000,)
(8000, 10000) (8000,)


### Modeling using scikit learn

In [17]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [18]:
nb.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [19]:
y_pred = nb.predict(X_test)

In [20]:
print("training accuracy: " ,nb.score(X_train,y_train))  #training accuracy
print("test accuracy: " ,nb.score(X_test,y_test))  #test accuracy

training accuracy:  0.86609375
test accuracy:  0.859125


In [21]:
# for submission
y2_pred = nb.predict(X2)

In [25]:
submission_df = pd.DataFrame(y2_pred,columns = ["label"])
index = submission_df.index
index.name = "Id"
submission_df.head(5)

label
Id       
0       0
1       0
2       0
3       1
4       1

In [36]:
submission_df.to_csv("submission.csv")

In [40]:
#for label in pos / neg
dict = {
    0 : "neg",
    1 : "pos"
}
submission_df = submission_df["label"].map(dict)

In [41]:
submission_df.to_csv("output.csv")